# Generated by Django 6.0.3 on 2026-04-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
