# Generated by Django 6.0.3 on 2026-04-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10, unique=True)),
                ('train_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('total_seats', models.PositiveIntegerField(default=100)),
                ('available_seats', models.PositiveIntegerField(default=100)),
                ('fare_per_person', models.DecimalField(decimal_places=2, max_digits=8)),
                ('travel_class', models.CharField(choices=[('SL', 'Sleeper'), ('3A', 'AC 3 Tier'), ('2A', 'AC 2 Tier'), ('1A', 'AC First Class')], default='SL', max_length=5)),
                ('days_available', models.CharField(default='Mon,Tue,Wed,Thu,Fri,Sat,Sun', help_text='Comma-separated days e.g. Mon,Wed,Fri', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='wallet', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_class',
            field=models.CharField(default='SL', max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.train'),
        ),
    ]
